/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Estructura;
/*
 * @author Arias,Tibanta, Armijo, Salazar J, Salazar S
 */
public class JPContactos extends javax.swing.JPanel {

    /**
     * Creates new form JFContactos
     */
    public JPContactos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFoto5 = new javax.swing.JLabel();
        jLabelFoto4 = new javax.swing.JLabel();
        jLabelFoto3 = new javax.swing.JLabel();
        jLabelFoto2 = new javax.swing.JLabel();
        jLabelFoto1 = new javax.swing.JLabel();
        jLabelDescripciones = new javax.swing.JLabel();
        jLabelCorreos = new javax.swing.JLabel();
        jLabelNumeros = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelNombres2 = new javax.swing.JLabel();
        jLabelNumeros2 = new javax.swing.JLabel();
        jLabelDescripciones2 = new javax.swing.JLabel();
        jLabelCorreos2 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(970, 630));
        setMinimumSize(new java.awt.Dimension(970, 630));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(970, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Francisco.png"))); // NOI18N
        add(jLabelFoto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 160, 160));

        jLabelFoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jonathan.png"))); // NOI18N
        add(jLabelFoto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 160, 160));

        jLabelFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jeremy.png"))); // NOI18N
        add(jLabelFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, 160));

        jLabelFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Santiago.png"))); // NOI18N
        add(jLabelFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 160, 160));

        jLabelFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marlow.png"))); // NOI18N
        add(jLabelFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 160, 160));

        jLabelDescripciones.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescripciones.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabelDescripciones.setText("Frontend developer/betatester                                                                     DataBase Developer                                                                            Frontend Develorer");
        jLabelDescripciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        add(jLabelDescripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 820, -1));

        jLabelCorreos.setText("        Jeremy.arias@epn.edu.ec                                                                             santiago.salazar@epn.edu.ec                                                              alexander.tibanta@epn.edu.ec");
        add(jLabelCorreos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabelNumeros.setText("0958690993                                                                                                   0968847408                                                                                             0968847408");
        add(jLabelNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabelNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNombres.setText("Jeremy Arias                                                                   Santiago Salazar                                                        AlexanderHOT69");
        add(jLabelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 20));

        jLabelNombres2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNombres2.setText("Jonathan Salazar                                                                Marlow Armijo             ");
        add(jLabelNombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 560, 20));

        jLabelNumeros2.setText("0988215014                                                                                                   0985476571            ");
        add(jLabelNumeros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        jLabelDescripciones2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescripciones2.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabelDescripciones2.setText("Frontend developer                                                                                     Backend Developer");
        jLabelDescripciones2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        add(jLabelDescripciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        jLabelCorreos2.setText("Jonathan.salazar@epn.edu.ec                                                                     Marlow.Armijo@epn.edu.ec");
        add(jLabelCorreos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(46, 152, 132));
        jLabelTitulo.setText("Contactos");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoContactos.jpg"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCorreos;
    private javax.swing.JLabel jLabelCorreos2;
    private javax.swing.JLabel jLabelDescripciones;
    private javax.swing.JLabel jLabelDescripciones2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFoto1;
    private javax.swing.JLabel jLabelFoto2;
    private javax.swing.JLabel jLabelFoto3;
    private javax.swing.JLabel jLabelFoto4;
    private javax.swing.JLabel jLabelFoto5;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelNombres2;
    private javax.swing.JLabel jLabelNumeros;
    private javax.swing.JLabel jLabelNumeros2;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
